---
name: prophet-env
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pip
  - fbprophet
  - pip:
      - pandas
      - schedule
      - prometheus_client
      - prometheus_api_client
      - tornado
      - dateparser
      - mlflow
      - numpy
      - keras
      - scikit-learn
      - plotly
      - scipy
      - tensorflow==2.2.0
      - tensorflow-estimator==2.2.0
      - tensorboard==2.2.2
      - tensorboard-plugin-wit==1.7.0
      - Flask==1.1.2
      - prometheus-flask-exporter==0.15.0
      - cloudpickle==1.5.0
      - pickleshare==0.7.5
      - redis
